# Generated by Django 5.0.1 on 2024-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_products_images_products_dropzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='images',
        ),
        migrations.AddField(
            model_name='documents',
            name='dropzone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_num',
            field=models.IntegerField(),
        ),
    ]
