# Generated by Django 5.0.2 on 2024-03-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images_uplodedfile_products_dropzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_photo',
        ),
    ]
